OPENAI_API_KEY = "your-openai-api-key-here"
DATABASE_URL = "sqlite:///./recruitment_bot.db"
VECTOR_STORE_TYPE = "openai"
OPENAI_ASSISTANT_ID = "your-assistant-id-here"
OPENAI_FILE_ID = "your-file-id-here"
DEBUG_MODE = "false"
